### ISSUE TITLE
idea dump

### ISSUE THREAD

**Issue by jprochazk** [ves-lang/ves#1]
After brainstorming, here is where the ideas should be placed. At some point, we'll condense them into a tour of the language + formal grammar and properly documented semantics.

Language outline:
Dynamically typed language made primarily for embedding into other applications. Bytecode, stack-based VM. 

Value types:
 - num (f64)
 - bool
 - str
 - none
 - object (struct)
 - fn
 - array
 - dict
 - result
 - ~~option~~
 - async/await (?)

Values are managed with reference counting instead of garbage collection (at least for now).

string interpolation:
```rust
f"{asdf}, {asdf} \{escaped}"
```

varargs/spread operator:
```
fn test(...args) {
  typeof(args) == "array"
  args[0] === a
  args[1] === b
  ...args // spread
}
test(a, b, c, ...d);
```

type comparison:
```
thing is map
thing is arr
thing is obj
thing is num
thing is str
thing is bool
thing is none
```

**Comment by optimalstrategy** [comment]
Some thoughts on the rough design of the compilation pipeline

## Pipeline Design (Draft)

1. [x] Scanner -- probably generated, should support UTF-8, escapes, and f-strings.
2. [x] Parser  -- possibly generated, maybe custom for better errors, should perform desugaring where needed.
    1. [ ] TODO: document all syntax desugaring.
3. [x] Resolver -- resolves keyword uses, lints for unused/unassigned variables, detects TCO eligibility if we support it.
    1. [x] Resolve break, continue, return, this (or self?), super.
    2. [x] Lint for unused variables.
    3. [x] Lint for unassigned variables.
    4. [x] TCO detection? Do we need TCO?
4. [x] Constant Folder -- pretty easy to implement, can also do const prop on `const` / `readonly` variables.
    1. [x] Basic constant folding for numeric, string, boolean expressions (Q: should this include type comparisons?).
    2. [x] Basic constant propagation on the `const` / `readonly` variables known at compile time.
    3. [x] Can support removing if statements and while/foor loops that will never be executed.
    4. [x] Can support removing the conditions for if statements / while loops that are always true.
5. [ ] Control flow analysis -- probably won't be in the MVP
    * Will need an efficient AST -> CFG -> AST conversion; might require introducing an intermediate IR that is easier to convert into.
    * We should be able to do simple escape analysis within function scopes (See the section on implementation details for more info).
        1. [ ] Detect which objects cannot escape the function scope (Note: what about tight for loops?)
            1. [ ] The object must not escape the function scope via function calls and stores.
            2. [ ] The object must not call any methods (since a method can leak `self`).
            3. [ ] The object must not have an initializer / constructor since it can leak `self`. This will need to be checked at runtime, because types exist at runtime (i.e. you can dynamically assign a new value to the variable holding the type).
        2. [ ] Allocate those objects using a bump allocator without reference counting.
        3. [ ] Emit a special instruction that would deallocate the object when it leaves the scope. This may require re-arranging locals within the scope to keep bump-allocated objects first so we can take the advantage of a `PopN` instruction that pops off multilple values at a time (i.e. pop off the special object with `PopDealloc`, then do a single `PopN`)
6. [x] Misc: AST printer pass for debugging
7. [ ] Misc: Code printer pass for debugging and possibly code formatting (the latter requires a concrete syntax tree that preserves whitespace and comments => should probably use rowan)
8. [ ] Compiler -- compiles the AST / IR to bytecode, emits the instructions for the optimizations performed / detected earlier, performs peephole optimizations
    1. [x] Basic support for the language syntax.
    2. [x] Should cache constants to preserve memory.
    3. [x] Should intern strings to preserve memory. Q: Should we nanbox small ascii strings? Runtime support for this sounds annoying, but what about the gains?
    4. [x] Should first emit symbolic bytecodes (let's calls this Bytecode IR or BIR for short) into basic blocks to enable peepohole optimizations.
    6. [ ] Optional: Should emit instructions for TCO calls
    7. [ ] Optinoal: Should emit instuctionss for non-escpaing objects
        * Some kind of `StackAlloc` instruction + some kind of `PopDealloc` instruction?
    8. [ ] Should perform peepohole optimizations on the BIR within the block. Should we run on every emit or at the end but until it hits a dead end? (TODO: move this into the implementation details section)
        1. [ ] Substitute `[Nil, Eq] => IsNil`.  Note: the `Nil` instruction just pushes a `nil` onto the stack.
        2. [ ] Substitute `[Nil, NEq] => IsNotNil`.
        3. [ ] Substitute `[SetLocal(x),  Pop] => SetLocalFast(x)`. Note (`SetLocalFast` is just like SetLocal but doesn't push the value onto the stack).
        4. [ ] Substitute `[SetLocalFast(x), GetLocal(x)] => SetLocal(x)`. Basically undoing the previous optimization, with the benefit that we got rid of that pop.
        5. [ ] Substitute `[GetLocal(x), GetLocal(x)] => [GetLocal(x), Copy]`. Not super useful, but could play better with the CPU cache if the VM stack is very large.
        6. [ ] Substitute `[GetLocal(x), GetField(y)] => GetFieldFast(x, y)`. Replaces a load + field access with a single instruction.
        7. [ ] Substitute `[GetLocalx), SetField(y)] => SetFieldFast(x, y)`. Replaces a load + field store with a single instruction.
        8. [ ] Substitute `[Pop,  Pop] => PopN(2)`. Replaces two `Pop` instructions with a single `PopN`.
        9. [ ] Substitute `[PopN(x),  Pop] => PopN(x + 1)`.
        10. [ ] Substitute `[Pop,  PopN(x)] => PopN(x + 1)`.
        11. [ ] Substitute `[PopN(x),  PopN(y)] => PopN(x + y)`.
        12. [ ] Arithmethic opts like `Mul` + `Add` => `MulAdd`?
9. [ ] VM
    1. [x] Stack-based (that's what in the book).
    2. [ ] Register-based? Codegen will be different since we will need to do register allocation to really take advantage of the registers.
    3. [ ] Optionally thread-safe?
    4. [x] NaN Boxing  
    5. [ ] Reference-counted GC w/ cycle detection?
        1. [ ] What and when should trigger the cycle collection algorithm?
            * [ ] On every reference drop, after checking the number of currently queued cycle roots?
            * [ ] On some reference drops, after checking the number of currently queued cycle roots, but only if the reference started a new root?
            * [ ] If the used memory exceeds some threshold. The tracked objects would be responsible for reporting their allocations/deallocations to the proxy allocator provided by the `CcContext`.
        2. [ ] Concurrent implementation

**Comment by jprochazk** [comment]
variables:
```rust
let x = 0 // immutable
mut y = 0 // mutable
```
immutable means the variable can't be re-assigned, it is not deep immutability - for that, there is object freezing via a const-cast:
```rust
let x = const(SomeStruct(a, b, c)) // immutable variable + frozen object
mut y = const(SomeStruct(a, b, c)) // mutable variable + frozen object
// can still reassign `y` to something else
y = 0;
```

**Comment by jprochazk** [comment]
variable shadowing
```rust
// all valid
let x = 0;
let x = 10;
{
  let x = 0;
}
```

**Comment by jprochazk** [comment]
for-each loop
```rust
for i = 0; i < 10; i += 1 {
  // ...
}
// special syntax for ranges, sugar for regular for loop
for i in 0..10 {
 // ...
}
// iterator protocol
for item in array {
  // ...
}
```
loop variables are assumed immutable, but you can shadow them
```rust
for item in array {
  item = 0; // error
  mut item = 0; // not an error
}
```

**Comment by jprochazk** [comment]
arrays and dictionaries
```rust
let arr = [];
arr.push(item);
arr.pop();
arr[10] = "test";
arr[1000000]; // crash
arr.get(10000000); // returns option instead of crashing
let dict = {};
dict["thing"] = "test";
dict["doesnt_exist"]; // crash
dict.get("doesnt_exist"); // returns option instead of crashing
```

**Comment by jprochazk** [comment]
structs
```rust
struct A(field0, field1, field2);
// with methods
struct A(field0, field1, field2) {
  test() { print "test" }
}
// with an 'init' block
struct A(field0, field1, field2) {
  init {
    if this.field0 > 10 { this.field0 = 0 }
  }
  test() { print "test" }
}

// semantics
let a = A(10, 5, 30);
// accessing non-existent fields causes a crash
a.field3; // crash
// it is possible to check for field existence with the `in` operator
if "field2" in a {
  print "it exists";
}
// it is possible to fetch a field via the index operator:
a["fie" + "ld2"]; // 5
// adding new fields is *not* possible.
// it may be supported in the future via some sort of reflection API
a.field3 = "test"; // crash

// type comparison for structs
let thing = A(nil, nil, nil);
if thing is A { ... }
```

**Comment by jprochazk** [comment]
error handling done with built-in result and option types
```rust
let good = ok("good");
let bad = err("bad");

let something = some("good");
let nothing = none;

fn optional() {
  return none;
}
fn result() {
  return err "test";
}
fn test() {
  // the '?' operator may be used to return if a value is err/none
  let value = optional()?;
  let value = result()?;
  // value is definitely 'ok/some' here, and it's already unwrapped for us
  value.do_something();
}

// since result and option are built-in types, they also have first-class checks built-in
if some(value) = optional() { ... }
if none = optional() { ... }
if ok(value) = result() { ... }
if err(value) = result() { ... }
```

**Comment by jprochazk** [comment]
Async/await
```rust
async fn test {
  // can use 'await' within here
  return await(query_some_api());
}
// top-level await is also supported
let response = await(test());
// this is *not* syntax sugar for "promises"
// these are futures, and they are polled when you `await` them
```

**Comment by optimalstrategy** [comment]
A NanBox implementation inspired by <https://github.com/Marwes/nanbox> and <http://craftinginterpreters.com/optimization.html>. See the last link for more info.

 # Overview
 Ves has four primitive values whose sizes allow us to take advantage of NaN Boxing, enabling efficient storage and type checking:
 1) Numbers  -- double precision floating point numbers (64 bits)
 2) Booleans -- true/false (1 bit)
 3) None -- none (0 bits, only needs a type tag)
 4) Pointers -- reference-counted pointers to heap-allocated Ves objects (48 bits).

 We can store all of these values inside a NaN in the manner outlined in the diagram below.
 The first bit of the NaN can be arbitrary, same as the 2 bits that follow the pointer payload, giving
 us 3 bits of free spaces or 2^3 = 8 possible states.

```text,ignore
              Quiet Bit
  Free Bit        │  2 Free Bits
     │            │ ┌┬───────────
     │            │ ││
    ┌▼────────────▼─▼▼──────────────────────────────────────────────────────┐
    │01111111_11111100_00000000_00000000_00000000_00000000_00000000_00000000│
    └─▲──────────▲─▲───▲───────────────────────────────────────────────────▲┘
      │          │ │   └───────────────────────────────────────────────────┘
      │          │ │                      48 Pointer Bits
      │ Exponent │ └──────┐
      └──────────┘        │
        11  bits   Intel FP Indef.
 ```

 We need at least 4 values to encode the 4 primitives types, and we would also like to encode whether a value
 is a variant of a result (ok, err). One possible encoding layout for this is the following:

 1. 000 - num (a normal f64 number)
 2. 001 - none
 3. 010 - bool ~if the 3rd and 4th pointer bits are 0, one of (ok, err) otherwise.~
 4. 011 - ptr
 5. 100 - ptr (ok)
 6. 101 - ptr (err)
TODO: think about applying the ok/err tagging to numbers

 ## Not a QNaN - num
 A regular 63-bit floating point number.

 ```text,ignore
  Tag = not a QNaN
   ┌────────────┐
   │            │
┌─▼────────────▼────────────────────────────────────────────────────────┐
│........_........_........_........_........_........_........_........│
└───────────────────────────────────────────────────────────────────────┘ 
```

 ## 001 - none
 Encodes a none value.

```
   Tag = 001             Pointer bits are all 0 = none
 ┌───────────────┐ ┌───────────────────────────────────────────────────┐
┌▼──────────────▼▼─▼───────────────────────────────────────────────────▼┐
│01111111_11111101_00000000_00000000_00000000_00000000_00000000_00000000│
└───────────────────────────────────────────────────────────────────────┘
```

 ## 010 - bool
 Encodes a bool that is possibly wrapped by an ok or err.

 ```text,ignore
     Tag = 010
  ┌──────────────┬┐                                              Value of the bool
  │              ││                                                     │
 ┌▼──────────────▼▼─────────────────────────────────────────────────────▼┐
 │01111111_11111110_........_........_........_........_........_.....YYX│
 └────────────────────────────────────────────────────────────────────▲▲─┘
                                                                      └┘
                                                                      00 Variant Bits are 00 = normal bool
                                                                      01 Variant Bits are 01 = ok
                                                                      10 Variant Bits are 10 = err
 ```

## 101, 110, 111 - ptr
Encodes a pointer: either a normal a pointer (011), a pointer behind an Ok (100), a pointer behind an Err (101).

```text,ignore
     Tag = 101      A regular pointer
 ┌───────────────┐ ┌───────────────────────────────────────────────────┐
┌▼──────────────▼▼─▼───────────────────────────────────────────────────▼┐
│11111111_11111101_XXXXXXXX_XXXXXXXX_XXXXXXXX_XXXXXXXX_XXXXXXXX_XXXXXXXX│
└───────────────────────────────────────────────────────────────────────┘
     Tag = 110      A pointer wrapped in an ok
 ┌───────────────┐ ┌───────────────────────────────────────────────────┐
┌▼──────────────▼▼─▼───────────────────────────────────────────────────▼┐
│11111111_11111110_XXXXXXXX_XXXXXXXX_XXXXXXXX_XXXXXXXX_XXXXXXXX_XXXXXXXX│
└───────────────────────────────────────────────────────────────────────┘
     Tag = 111      A pointer wrapped in an err
 ┌───────────────┐ ┌───────────────────────────────────────────────────┐
┌▼──────────────▼▼─▼───────────────────────────────────────────────────▼┐
│11111111_11111111_XXXXXXXX_XXXXXXXX_XXXXXXXX_XXXXXXXX_XXXXXXXX_XXXXXXXX│
└───────────────────────────────────────────────────────────────────────┘
```

**Comment by jprochazk** [comment]
Bytecode operations should be forced to keep the stack locally balanced, like in the JVM and CLR, which would allow us to erase the VM stack in a potential JIT implementation (https://softwareengineering.stackexchange.com/questions/389407/how-are-registers-implemented-in-vms/389411#389411)

**Comment by jprochazk** [comment]
`some` and `none`

* `some` is not a value, only a type. it can be used with the type equality operator (binary `is`), to check if a value is not `none`
* `none` is both a type and a value. it semantically replaces `nil`/`null`/similar in the language

`nil` itself is removed. this raises a problem: how do you differentiate between a field which does not exist, and has a `none` value? the answer is adding a built-in field existence check. we'll do this via the binary `in` operator.

```rust
fn map(x, f) {
  // `is some` checks if `x` is not `none`
  if x is some { f(x) }
}
map(10, fn(v) => print v); // prints 10
map(none, fn(v) => print v); // doesn't print

struct Vector3(x, y, z);
let vec = Vector3(0.5, 1.0, 0.5);
if !("w" in vec) {
  print vec; // prints 'Vector3 { x: 0.5, y: 1.0, z: 0.5 }'
}
```

**Comment by jprochazk** [comment]
error handling update: `try` keyword

in order to disambiguate between `?` for error propagation and optional chaining, the `try` keyword will be introduced with the following behavior:

```rust
fn may_fail(should_fail) {
  if should_fail { err("failed!") }
  else { ok("did not fail!") }
}

fn test1 {
  let v = try may_fail(true);
  // if the call does not result in an error, the value will be automatically unwrapped:
  print v;
  // the above error will propagate, as if you did:
  let v = may_fail(true);
  if err(v) = v { return err(v) }
  let v = v.unwrap();
}

fn test2 {
  let v = try may_fail(false);
  // v is unwrapped here
  print v;
}

test1(); // does not print
test2(); // prints "did not fail!"
```

**Comment by jprochazk** [comment]
default arguments:
* may not be followed by non-default arguments

```rust
fn test1(a, b = none, c) { ... } // error at compile time
fn test2(a, b, c = none) { // valid
  if c is none { print a, b }
  else { print a, b, c }
}
test2(0, 5); // prints '0 5'
test2(0, 5, 10); // prints '0 5 10'
```

**Comment by jprochazk** [comment]
optional chaining:
* only valid for property access, not valid for left-hand side of any kind of assignment

```rust
struct A(v = none);
struct B(a = none);
struct C(b = none);

let test = C(B(none))
test.b.a.v // error - field `v` does not exist on type `none`
test?.b?.a?.v // returns 'none'
use(test);

fn use(v) {
  // here is where `is some` shines
  if test?.b?.a?.v is some {
    print test.b.a.v
  } else {
    print "test.b.a.v is none"
  }
}
```

**Comment by jprochazk** [comment]
closure semantics = capture by value:
```rust
fn a() {
  var v = "before";
  fn b() {
    v = "after";
    print v;
  }
  b(); // should print "after"
  print v; // should print "before"
}
a();
```
other dynamic languages tend to have capture-by-variable semantics (JS, python), but we've decided to not include this behavior. the reasoning is that it allows users to more easily reason about their programs- a closure won't have its variable mutated by some external actor, far away from where the closure is declared. at the same time, it still maintains the behavior most users expect from closures:
```rust
fn make_counter(start, step) {
  return fn () {
    start += step;
    return start;
  }
}
let counter = make_counter(10, 5);
print counter(); // 15
print counter(); // 20
print counter(); // 25
```
not to mention you can *still* imitate capture by variable semantics by wrapping your value inside of an object:
```rust
fn wrap(value) {
  return { value };
}
fn make_container(value) {
  var obj = wrap(value);
  var set = fn (v) => obj.value = v;
  var get = fn () => obj.value;
  return { get, set };
}
let container = make_container(10);
print container.get(); // 10
container.set(50);
print container.get(); // 50
```

**Comment by jprochazk** [comment]
We've pretty much settled the overall design, and are heading towards an implementation, so I'll close this.
